Fix mjml build and add NODE_ENV for build
paralect/koa-api-starter pull request #120
Opened 2021-09-09 15:28 UTC by KirdunVlad

2021-09-09 15:41 UTC, NesterenkoNikita requested changes

2021-09-09 15:41 UTC, NesterenkoNikita commented on package.json
> +    "build": "NODE_ENV=production run-s build:**",
Not sure about this line

2021-09-27 08:42 UTC, Oigen43 approved these changes

2021-09-27 08:45 UTC, NesterenkoNikita approved these changes

2021-09-27 08:45 UTC, merged