Add method 'Promise limit' for partially migration
paralect/koa-api-starter pull request #128
Opened 2021-12-03 12:34 UTC by Fruneen

2021-12-03 14:11 UTC, Oigen43 approved these changes

2021-12-03 16:14 UTC, Oigen43 commented
@Fruneen Let's add an example of using this method, just write migration in migrations/1.js and comment it with //

2021-12-06 15:55 UTC, KuhArt requested changes

2021-12-06 15:55 UTC, KuhArt commented on src/migrations/migration.service.js
> +service.promiseLimit = async (collection = [], limit, operator) => {
I think `documents` instead of `collection`  will be more suitable

2021-12-06 15:55 UTC, KuhArt commented on src/migrations/migration.service.js
> +  await chunks.reduce((init, chunk) => {
You can remove async/await and just return a promise.

2021-12-08 23:52 UTC, KuhArt approved these changes

2021-12-08 23:53 UTC, merged